### ISSUE TITLE
无法使用cf-clash透明代理，能否添加ipset模块；谢谢

### ISSUE THREAD

**Issue by xxtt8812** [KryptonLee/e900v22c-CoreELEC#12]
19.5版本，无法使用cf-clash透明代理，能否添加ipset模块；谢谢
https://github.com/changfeng2021/cf-clash

**Comment by KryptonLee** [comment]
功能问题请提交到官方CoreELEC，本项目仅针对CoreELEC适配e900v22c进行相应修改
