### ISSUE TITLE
貌似用无线连接时播放蓝光原盘时卡顿?

### ISSUE THREAD

**Issue by motiyb** [KryptonLee/e900v22c-CoreELEC#13]
我的设备是e900v22c，刷的版本是19.5 rc3。播放的文件在NAS上，通过NFS协议访问。

卡顿的现象是: 播放NAS的其他文件没有问题，但是播放那种带Index (原盘?) 的电影就会卡顿。切换成有线后就流畅了。U盘或者mmc 都是一样的状况。

AP上面显示无线连接速率是433Mhz，貌似不像是因为网络速度上限导致的。因为播放一些高码率的电影，用有线的话 大部分时间流畅，偶尔需要缓存下，但是用无线的话，一直都处于卡顿状态，感觉像是那种CPU占用太高导致的卡顿。

想请问下是不是有什么特别的设置要做，或者有没有什么思路可能可以解决这个问题，我都可以去尝试下。 

谢谢！

**Comment by motiyb** [comment]
绕了好大一圈，最后发现还是网络速度不够的问题.... 无线连接433Mhz的速度还是不够播放原盘.... e900v22c虽然是2x2的无线，貌似433Mhz 只是1x1的速率。

**Comment by cnhap** [comment]
> 绕了好大一圈，最后发现还是网络速度不够的问题....无线连接433Mhz的速度还是不够播放盘....e900v22c虽然是2x2的无线，貌似433Mhz只是1x1的速率，有法律支持到866M或780M的速度不？

我想刷CoreELEC到emmc  找到这里的 还没有找到刷机的方法 另外我用刷的安卓的固件 显示是会显示780Mps 的

**Comment by KryptonLee** [comment]
驱动问题，现在5621ds的WIFI驱动并不完善，同时传输多个文件时容易卡顿。除非有更完善的驱动源码流出，不然很难有改善
