### ISSUE TITLE
升级coreelec版本

### ISSUE THREAD

**Issue by darescloud** [KryptonLee/e900v22c-CoreELEC#14]
系统自动升级19.5正式版以后，会丢失WiFi驱动

**Comment by wishday** [comment]
从这个系统升级到官方系统  当然会丢wifi驱动了
这个系统特点就是集成了  wifi和红外的DTB配置文件
希望[KryptonLee]大神能跟进CE官方版本，提供修改好的新版本镜像吧

**Comment by aspack00** [comment]
在 CoreELEC 安装好以后，从界面的左上角 " 系统 " ( 齿轮图标 ) -->CoreELEC-，把自动升级改成Manual
![image](https://github.com/KryptonLee/e900v22c-CoreELEC/assets/3943619/7abb8a20-ba29-4539-aa21-f2ea0eba6217)

**Comment by KryptonLee** [comment]
自动升级会将修改后自启动WIFI模块的服务恢复为官方的，导致服务不能自启动
