### ISSUE TITLE
能搞定ceemmc写入emmc吗

### ISSUE THREAD

**Issue by wishday** [KryptonLee/e900v22c-CoreELEC#15]

**Comment by cnhap** [comment]
我也想知道 如何 刷入emmc  盒子打算放电视后面 每次开机要按遥控启动有点不方便.

**Comment by KryptonLee** [comment]
19版本需要先执行一次双启动写入，然后在执行一次单启动写入（该版本的ceemmc有bug，直接写入单启动会导致系统启动失败），20版本直接执行单启动写入即可。
