### ISSUE TITLE
能否添加rtl8822cs支持

### ISSUE THREAD

**Issue by tangmuyang** [KryptonLee/e900v22c-CoreELEC#3]
s905l3a方案，为了多系统兼容或补wifi功能，改wifi模块为rlt8822cs较多。高手已适配了原版wifi，请求添加一下rtl8822cs的支持，现在大佬的coreelec刷入U盘，启动后是无识别8822的wifi与蓝牙的，刷官方版也无法识别。在atv，emuelec下可以正常使用wifi，蓝牙。

**Comment by KryptonLee** [comment]
没有硬件测试，不作考虑，emuelec的内核都是引用coreelec的，emuelec可以的话对应版本的coreelec理论上也可以
