### ISSUE TITLE
Installation to Internal eMMC

### ISSUE THREAD

**Issue by Jerry6666** [KryptonLee/e900v22c-CoreELEC#7]
Hi KryptonLee,

I really appreciate your help in develping this repo.

Error always occurs when using command _ceemmc -x_ for installation to internal eMMC (CoreELEC-19.5_rc2-2022.09.08).
> Error opening file for writing '/dev/reserved'!
> Failed to write the new partition table to eMMC!

From the release note of CoreELEC 20.0-Nexus_alpha3 (September 15th, 2022), it says that 
> Fixed ceemmc error: Error opening file for reading '/dev/reserved'

I tried to use _/usr/sbin/ceemmc_ from CoreELEC 20.0-Nexux_alpha3 in CoreELEC-19.5_rc2-2022.09.08, and it works.

Just for your reference.

**Comment by climbL** [comment]
> Hi KryptonLee,
> 
> I really appreciate your help in develping this repo.
> 
> Error always occurs when using command _ceemmc -x_ for installation to internal eMMC (CoreELEC-19.5_rc2-2022.09.08).
> 
> > Error opening file for writing '/dev/reserved'!
> > Failed to write the new partition table to eMMC!
> 
> From the release note of CoreELEC 20.0-Nexus_alpha3 (September 15th, 2022), it says that
> 
> > Fixed ceemmc error: Error opening file for reading '/dev/reserved'
> 
> I tried to use _/usr/sbin/ceemmc_ from CoreELEC 20.0-Nexux_alpha3 in CoreELEC-19.5_rc2-2022.09.08, and it works.
> 
> Just for your reference.

I can't find /usr/sbin/ceemmc. Could you explain how to change this file? Thanks!

**Comment by KryptonLee** [comment]
> Hi KryptonLee,
> 
> I really appreciate your help in develping this repo.
> 
> Error always occurs when using command _ceemmc -x_ for installation to internal eMMC (CoreELEC-19.5_rc2-2022.09.08).
> 
> > Error opening file for writing '/dev/reserved'!
> > Failed to write the new partition table to eMMC!
> 
> From the release note of CoreELEC 20.0-Nexus_alpha3 (September 15th, 2022), it says that
> 
> > Fixed ceemmc error: Error opening file for reading '/dev/reserved'
> 
> I tried to use _/usr/sbin/ceemmc_ from CoreELEC 20.0-Nexux_alpha3 in CoreELEC-19.5_rc2-2022.09.08, and it works.
> 
> Just for your reference.

Maybe my answer for this issue can help you #1
