### ISSUE TITLE
写入emmc有什么注意的吗

### ISSUE THREAD

**Issue by Bitcion** [KryptonLee/e900v22c-CoreELEC#8]
执行/flash/installtoemmc执行写入EMMC的命令。(需要注意的是9.0.2以上版本使用/flash/installtoemmc，旧版使用/flash/installtointernal）

这样操作没问题吧

**Comment by KryptonLee** [comment]
那是针对Phiconn N1的特定方法，对其它盒子不一定适用，方法参见已解决的issue #1
